### ISSUE TITLE
Image Data Preparation

### ISSUE THREAD

**Issue by jingweitan** [cpystan/Wsi-Caption#1]
Thanks for your amazing work. I'm going to test your method with my dataset. Could you please explain how you prepare the WSI with HIPT pretrained model for use in your model? Do you first crop the WSIs into 4096x4096 patches and then extract and save their features? These extracted features would then be fed into the model. Am I correct?

**Comment by cpystan** [comment]
Yes, you are exactly right. We cut 256–shape patches at 20x magnification.



---Original---
From: "Jing ***@***.***&gt;
Date: Fri, Mar 15, 2024 14:18 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [cpystan/Wsi-Caption] Image Data Preparation (Issue #1)




 
Thanks for your amazing work. I'm going to test your method with my dataset. Could you please explain how you prepare the Whole Slide Images (WSIs) for use in the model? Do you first crop the WSIs into 256x256 patches and then extract and save their features? These extracted features would then be fed into the model. Am I correct?
 Looking forward to your response.

**Comment by jingweitan** [comment]
So, it's mean that you crop the patches into 256x256 and then extracted the features from the Stage1 of the HIPT? Is it that the feature of the patches from a single WSI will be then concatenated and save in the .pt file right?

**Comment by cpystan** [comment]
> So, it's mean that you crop the patches into 256x256 and then extracted the features from the Stage1 of the HIPT? Is it that the feature of the patches from a single WSI will be then concatenated and save in the .pt file right?

right

**Comment by jingweitan** [comment]
Thank you for your quick response. Have a nice day.

**Comment by cpystan** [comment]
Solved the question.
