### ISSUE TITLE
Semantic extraction in slide-level tasks

### ISSUE THREAD

**Issue by lsnls** [cpystan/Wsi-Caption#10]
Hello, authors! Thank you for selflessly sharing this great work!

In the `Results` section, you mentioned `We have observed that some generated reports contain the descriptions for carcinoma subtyping or Her2 prediction so that the corresponding result can be directly extracted from the text`. You said `some`, not `all`. So what should be done if the report generated for some samples does not include descriptions of carcinoma subtyping and Her2 prediction?

Looking forward to your reply!

Best Regards,
Suoni

**Comment by cpystan** [comment]
If the caption does not include related descriptions, we will ignore this case.

**Comment by lsnls** [comment]
I got it, thank you!
