### ISSUE TITLE
Query on Environment Configuration, Looking Forward to Your Reply

### ISSUE THREAD

**Issue by blz822** [cpystan/Wsi-Caption#11]
Dear authors,
I'm currently working on reproducing the experiments described in your paper. I'm following the basic environment requirements you provided in the paper, which mentions using Linux (tested on Ubuntu 18.04), NVIDIA GPU (tested on Nvidia GeForce A100) with CUDA 12.0, and Python 3.8. However, I'm encountering some difficulties during the setup process as these requirements seem a bit too general for me to fully configure the environment accurately.
I would really appreciate it if you could provide more detailed information about the environment setup. For example:
What are the specific versions of the Python libraries (such as PyTorch, TensorFlow, or other key libraries used in the project) that are required?
Are there any additional system software or tools that need to be installed and configured? If so, what are their details and versions?
Are there specific environment variables that need to be set for running the models or experiments smoothly?
Any further details about the environment that you think could be helpful for a successful reproduction would be great.
Thank you very much for your time and I'm looking forward to your reply. 

Best regards!

**Comment by cpystan** [comment]
torch                              1.10.0+cu111
torchmetrics                       1.0.0
torchvision                        0.11.0+cu111
PyMuPDF                            1.22.5
pytesseract                        0.3.10

If any questions, free to contact me.

**Comment by blz822** [comment]
thanks very much
