### ISSUE TITLE
Decompression Issue with Uploaded Data

### ISSUE THREAD

**Issue by ElvinKim** [cpystan/Wsi-Caption#2]
Thank you for your amazing work. I have a question about the data you uploaded. The data you posted is not decompressing; could you please check if there is a problem with the file?
![Screenshot 2024-03-28 at 4 48 35 PM](https://github.com/cpystan/Wsi-Caption/assets/12638561/5bed4e85-b9aa-4132-b852-be35ccbccfff)

**Comment by cpystan** [comment]
> Thank you for your amazing work. I have a question about the data you uploaded. The data you posted is not decompressing; could you please check if there is a problem with the file? ![Screenshot 2024-03-28 at 4 48 35 PM](https://private-user-images.githubusercontent.com/12638561/317912754-5bed4e85-b9aa-4132-b852-be35ccbccfff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTIxOTEsIm5iZiI6MTcxMTY5MTg5MSwicGF0aCI6Ii8xMjYzODU2MS8zMTc5MTI3NTQtNWJlZDRlODUtYjlhYS00MTMyLWI4NTItYmUzNWNjYmNjZmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA1NTgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MDZiMTBmZGNjZGYyNGY3MGVjYTU3MjJjNjBiNDRkMzI5NTQyMDExY2Q0M2JiYjRmZTFjOTNhN2Q1M2MyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MbBwZT3eGJOmbjTheJkGw3oGvrenRRxt65oTfkQtre4)

I use RAR in Windows to decompress and it is ok. Maybe you can try again?

**Comment by ElvinKim** [comment]
Thanks for the quick response.

I was able to unzip it using 'The Unarchiver' on my Mac.!
