### ISSUE TITLE
splits划分

### ISSUE THREAD

**Issue by yucLucas** [cpystan/Wsi-Caption#3]
请问可以开源其他数据集的split_path <PATH to the directory containing the train/val/test splits>划分吗，另外我还想咨询下数据集中的svs图片是怎么选取的，似乎并没有把数据集中所以svs图片用上，我一开始以为全是01z的，但发现几张是01A的svs图片

**Comment by cpystan** [comment]
1.其他数据集具体指的是？
2.我选用了含字符‘DX’的全场图文件。 在TCGA中，DX代表的是diagnostic slide。

**Comment by yucLucas** [comment]
> 1.其他数据集具体指的是？ 2.我选用了含字符‘DX’的全场图文件。 在TCGA中，DX代表的是diagnostic slide。

例如BRCA数据集中的svs图片总共是 3,111 个，但根据splits_0.csv文件发现，作者您们只用了1041个，我想问是怎么选取的。
然后想问是否可以提供diagnostic slide除了已有的BRCA数据集，剩下数据集的splits.csv文件，如TCGA-ACC、TCGA-BLCA、TCGA-CESC等。
本质是不知道怎么挑选用于训练的svs图片

**Comment by cpystan** [comment]
TCGA-14-0786-01Z-00-**DX**2.9dd57cfe-f467-4796-a491-48b737a6248c.svs 含有标题中加粗的DX的全场图文件是我们需要的，三千多个svs文件其中有一大部分是TS（tissue slide）。 在做全场图的任务的时候，一般选用DX（diagnostic slide）。

**Comment by yucLucas** [comment]
> TCGA-14-0786-01Z-00-**DX**2.9dd57cfe-f467-4796-a491-48b737a6248c.svs 含有标题中加粗的DX的全场图文件是我们需要的，三千多个svs文件其中有一大部分是TS（tissue slide）。 在做全场图的任务的时候，一般选用DX（diagnostic slide）。
哦哦 我懂了 第一次提问，谢谢你的耐心解答
